package ExtraDisks;

import net.minecraft,creativetab.CreativeTabs;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.EventHandler;
import cpw.mods.fml.common.Instance;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;

@Mod(modid = "ExtraDisks", name = "Extra Music Disks", version = "1.0.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class ExtraDisks {
@Instance("ExtraDisks")
public static ExtraDisks instance = new ExtraDisks();
public static CreativeTabs extradisksTab = new extradisksTab();
@EventHandler
      public void PreInit(FMLPreInitializationEvent event)
      {
	  ModMetadata modMeta = event.getModMetadata();
	  modMeta.authorList = Arrays.asList(new String[] {"Rongmario"});
	  modMeta.autogenerated = false;
	  modMeta.credits = "Rongmario";
	  modMeta.description = "Mod that aims to add more music to the world of Minecraft :3";
	  modMeta.url = "https://github.com/Rongmario/ExtraMusicDisks";
	  }
@EventHandler
public void Init (FMLInitializationEvent event)
{
}
}
